### ISSUE TITLE
"Failed to drop or create the database"

### ISSUE THREAD

**Issue by donquixote** [openeuropa/drupal-site-template#59]
_(version debfcbd1284644faa5fecf2cfcb9ec5af14e7126)_

I followed the normal instructions.

The following command

    docker-compose exec web ./vendor/bin/run toolkit:install-clean

gives me

```
In SiteInstallCommands.php line 367:
                                                   
  Failed to drop or create the database:
```

I'd say it probably has problems connecting to the db.

## Related issue
https://github.com/openeuropa/drupal-site-template/issues/31

The solution proposed there is to use something other than the normal install process.
But we should make this work with the recommended install process with docker.

**Comment by brummbar** [comment]
This is caused by the Docker services that are not yet completely initialised. The speed of starting the services depends on the host machine where the commands are run.
Most of the time, it's just enough to wait a few seconds before issuing the install commands.
This is a Docker typical behaviour, but we will try to add this info in documentation.

**Comment by donquixote** [comment]
Interesting.
I am not sure how much time I let pass the last time. Either way I tried again now and it worked. So I suppose you are right.
